### ISSUE TITLE
Add A Demo Using ANT

### ISSUE THREAD

**Issue by opticyclic** [vngx/vngx-jsch#10]
It is suggested here that this project is a drop in replacement for JSch.
http://stackoverflow.com/a/5366283/1000011

However, if I replace my jsch jar with yours I get the following error:
Problem: failed to create task or type scp
Cause: Could not load a dependent class com/jcraft/jsch/Logger
       It is not enough to have Ant's optional JARs
       you need the JAR files that the optional tasks depend upon.
       Ant's optional task dependencies are listed in the manual.

How is your library supposed to work with ANT?

**Comment by scott2449** [comment]
You can use something like Ivy with ANT and the existing maven repos / artifacts. The build process here is just included here to ease development and contribution. We aren't going to supply examples every build / dependency system out there. We'd have a travis.yaml, team city config, etc, etc ... The jar works in isolation but IS NOT a drop in replacement for JSCH. It's very close in order to reduce learning curve but it is in every sense of the word a fork.
